# Generated by Django 5.2 on 2025-05-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
