name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate database
        run: python manage.py migrate
      - name: Collect static files
        run: python manage.py collectstatic --noinput
      - name: Restart Gunicorn (via SSH or API)
        run: ssh user@geek168 "sudo systemctl restart portfolio"